version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Cobra_535"
      ACCEPT_EULA: "Y"

#docker-compose up -d --build
#docker exec -it 26fac6ca2e79 sh
#docker exec -it 26fac6ca2e79 bash
#/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Cobra_535
